name: lpb_insurance
description: "LBD Insurance"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localization: ^0.3.1
  flutter_bloc: ^9.1.0
  retrofit: ^4.4.2
  uuid: ^4.5.1
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  intl: ^0.19.0
  device_info_plus: ^11.3.0
  package_info_plus: ^8.3.0
  logger: ^2.0.2
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.14
  get: ^4.6.6

  # DI
  injectable: ^2.3.0
  get_it: ^7.6.4

  dio: ^5.3.2
  rxdart: ^0.27.7
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.2
  json_serializable: ^6.7.1
  flutter_svg_provider: ^1.0.6
  lottie: ^2.6.0
  pull_to_refresh: ^2.0.0
  flutter_native_splash: ^2.3.8
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  path_provider: ^2.1.2
  flutter_easyloading: ^3.0.5

  firebase_messaging: ^15.2.4
  firebase_core: ^3.12.1
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  intl_utils: ^2.8.4
  retrofit_generator: ^7.0.8
  flutter_flavorizr: ^2.2.1
  flutter_launcher_icons: ^0.13.1
  qr_flutter: ^4.1.0
  mqtt_client: ^9.6.4
  bloc_test: ^10.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/anim/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_assets_generator:
  output_dir: generated
  auto_detection: true
  named_with_parent: true
  output_filename: assets
  class_name: Assets
flutter_intl:
  enabled: true
  main_locale: vi

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
      bundleIdSuffix: ".$flavor"

  flavors:
    uat:
      app:
        name: "LPB Insurance UAT"
      android:
        applicationId: "com.example.lpbinsurance.uat"
      ios:
        bundleId: "com.example.lpbinsurance.uat"

    prod:
      app:
        name: "LPB Insurance"
      android:
        applicationId: "com.example.lpbinsurance"
      ios:
        bundleId: "com.example.lpbinsurance"
